name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compile-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install ESPHome
        run: pip install --upgrade esphome
      - name: Validate example YAML
        run: esphome config example/hello_world_m5papers3.yaml
